function val = ComputeVonMisesStress(cartesianStress)
	global domainType_;
	switch domainType_
		case '2D'
			val = sqrt( cartesianStress(:,1).^2 + ...
				cartesianStress(:,2).^2 - cartesianStress(:,1).*...
					cartesianStress(:,2) + 3*cartesianStress(:,3).^2 );
		case '3D'
			val = sqrt( 0.5*( (cartesianStress(:,1)-cartesianStress(:,2)).^2 + ...
				(cartesianStress(:,2)-cartesianStress(:,3)).^2 + (cartesianStress(:,3)...
					-cartesianStress(:,1)).^2 ) + 3*( cartesianStress(:,6).^2 + ...
						cartesianStress(:,4).^2 + cartesianStress(:,5).^2 ) );
	end		
end
