function val = ElementStruct()
	val = struct(					...
	'ith',						0, 	...
	'property',					0,	...		%% 0==interior elements; 1==boundary elements
	'relativeNodIndex',			[],	...
	'relativeNodCoord',			[], ...
	'centerCoord',				[], ...
	'relativeDOFsIndex',		[], ...
	'adjacentElements', 			[], ...
	'relativeLattices',			[], ...
	'relativePSL',				[]	...		%% 0==maxPSL; 1==minPSL; else == 'wrong'
	);
end