function val = Plane144()
	%% 2D plane element with 1st-order shape function, 4 nodes and 4 Gaussian integral points
	val = struct(	...
		'numNode',				4, 	...
		'numNodeDOFs',			2, 	...
		'numGIPs',				4,	...
		'numStrainComponents',	3,	...
		'numStressComponents',	3,	...
		'numNorAdjElements',	8	...	%%number of normal adjacent elements, 3*3-1		
	);
end