function val = ScalarFieldForVolumeRendering()
	val = struct(	...
		'eleList',		'default',	...
		'scalarFiled', 	[], ...
		'shiftingTerm',	[],	...
		'scalingFac',	'default',	...
		'dispOpt',		'default',	...
		'viewAngle',	3	...
	);
end