function val = Solid188()
	%% 3D solid element with 1st-order shape function, 8 nodes and 8 Gaussian integral points
	val = struct(					...
		'numNode',				8, 	...
		'numNodeDOFs',			3, 	...
		'numGIPs',				8,	...
		'numStrainComponents',	6,	...
		'numStressComponents',	6,	...
		'numNorAdjElements',	26	...	%%number of normal adjacent elements, 3*3*3-1
	);
end
