function val = Data_ArbitraryMeshStruct()
	val = struct(...
		'state',						0,	...
		'meshType',						[],	...
		'numNodes',						0,	...		
		'nodeCoords',					[],	...
		'numElements',					0,	...		
		'eNodMat',						[],	...
		'nodeState',					[],	...
		'refSize',						0,	...
		'boundaryNodeCoords',			[],	...
		'boundaryPatchNodMat',			[]	...
	);
end